before_install:
  - gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
bundler_args: --clean --deployment --jobs=$(nproc) --without development production performance
cache: bundler
dist: trusty
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-5.2.x
  - gemfiles/Gemfile.rails-6.0.x
jdk:
  - openjdk8
language: ruby
matrix:
  fast_finish: true
  include:
    - rvm: 2.5.8
      gemfile: gemfiles/Gemfile.rails-6.1.x
  allow_failures:
    - rvm: rbx-3
    - rvm: 2.5.8
      gemfile: gemfiles/Gemfile.rails-6.1.x
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - jruby-9.2.16.0
  - rbx-3
sudo: required
